useDotenv: true
service: nest-serverless-lambda-apartment-bot
plugins:
 - 'serverless-plugin-typescript'
 - serverless-offline
 - serverless-dotenv-plugin

provider:
 name: aws
 runtime: nodejs12.x
 apiGateway: 
  shouldStartNameWithService: true

functions:
 main: # The name of the lambda function
   # The module 'handler' is exported in the file 'src/lambda'
   handler: src/lambda.handler
   events:
     - http:
         method: any
         path: /{any+}
     - schedule: cron(0/15 2-23 * * ? *)